spring:
  application:
    name: template
  profiles:
    active: local
  flyway:
    baseline-version: 0
    enabled: true
    baseline-on-migrate: true
setting:
  max-num-per-page:
    - 30
    - 50
    - 100
  max-num-per-query: 3000